version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: quiz-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: quizdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 5s
      retries: 10
      start_period: 20s
    networks:
      - quiz-net

  backend:
    image: deepali2712/myquizapp-backend:latest   
    container_name: quiz-api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8010:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@mysql:3306/quizdb
    networks:
      - quiz-net

  frontend:
    image: deepali2712/myquizapp-frontend:latest
    container_name: quiz-ui
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - quiz-net

volumes:
  mysql_data:

networks:
  quiz-net:
    driver: bridge
