version: "3.9"

services:
  couchdb:
    image: couchdb:3.3
    container_name: couchdb
    restart: unless-stopped
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data    
    networks:
      - reactdb_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/"]
      interval: 10s
      retries: 10
      start_period: 10s

  backend:
    image: deepali2712/react-node-couchdb-backend:latest
    container_name: backend
    restart: unless-stopped
    environment:
    - PORT=5000
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=password
    - COUCHDB_HOST=couchdb
    - COUCHDB_PORT=5984
    ports:

      - "5000:5000"
    depends_on:
      couchdb:
        condition: service_healthy
    networks:
      - reactdb_net

  frontend:
    image: deepali2712/react-node-couchdb-frontend:latest
    container_name: frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://backend:5000
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - reactdb_net

volumes:
  couchdb_data:
    external: true
    name: react-node-couchdb_couchdb-data   

networks:
  reactdb_net:
    driver: bridge
